// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xSFix4ciVzaBkzAQv3ztHUFm5Nnr1mA',
    appId: '1:810184464957:web:e7c290e5f94899ccdf2854',
    messagingSenderId: '810184464957',
    projectId: 'roam-mate',
    authDomain: 'roam-mate.firebaseapp.com',
    storageBucket: 'roam-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0BTa9-j--bJx4mohMfMrYuDoaz_8LX6A',
    appId: '1:810184464957:android:d290ca743a79d827df2854',
    messagingSenderId: '810184464957',
    projectId: 'roam-mate',
    storageBucket: 'roam-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDx-KNT_y3k2FeQ8jwitDOF_VPGoYvqRM',
    appId: '1:810184464957:ios:ada91a9b7b27efb6df2854',
    messagingSenderId: '810184464957',
    projectId: 'roam-mate',
    storageBucket: 'roam-mate.appspot.com',
    iosClientId: '810184464957-l4g6me425jhcqd3e7rj6bg199b3o801j.apps.googleusercontent.com',
    iosBundleId: 'com.example.roamMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDx-KNT_y3k2FeQ8jwitDOF_VPGoYvqRM',
    appId: '1:810184464957:ios:1b41408b5ada837fdf2854',
    messagingSenderId: '810184464957',
    projectId: 'roam-mate',
    storageBucket: 'roam-mate.appspot.com',
    iosClientId: '810184464957-7lnuatfv9drujia27sb4e8bmt6a563fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.roamMate.RunnerTests',
  );
}
